### ISSUE TITLE
String too long (panic: unknown in Fupdate)

### ISSUE THREAD

**Issue by aksr** [phonologus/edam#3]
Just out of curiosity, I tried to do this with a not-so-big file (~10MB)

```
$ edam not-so-big-file
-. not-so-big-file
,x/ /c/./
?string too long
?string too long
edam: panic: unknown in Fupdate
Aborted
```
Needless to say, `p9p sam` and `deadpixi sam` don't have this limit. One more limit that needs to be removed.

**Comment by phonologus** [comment]
Interesting. I can't reproduce this behaviour on my system (M3 Macbook Air). I've used `edam` built with `clang`, and with Homebrew `gcc` (i.e. not the `gcc` wrapper around `clang`, but the "real" `gcc`).  I won't have access to my Linux box until next week, at which point I'll see what's going on with a Linux build.

**Comment by phonologus** [comment]
I used an ASCII file that was exactly 10MB (generated by `base64 -i /dev/urandom | head -c 10000000`). My Mac build of `edam` was able to accomplish substitutions like `,x/Q/c/\n/` successfully without abending.

Unfortunately there are three or four (unrelated) places in the source code that raise the "string too long" error, and I can't debug against a Linux build until next week.

**Comment by phonologus** [comment]
OK, so I have run the same test on my Linux build (not in a VM, current Fedora running on the metal on a Thinkpad T14s), and a 10MB ASCII file generated by `base64 -i /dev/urandom | head 10000000`, and I can't reproduce the abend. It's working fine. My linux `cc` is `(GCC) 13.3.1 20240522 (Red Hat 13.3.1-1`. Is there a weird byte in your input file (if so, `edam` needs to catch it gracefully)?

**Comment by phonologus** [comment]
Yes, that file triggers an abend, on both Mac and Linux

**Comment by phonologus** [comment]
I fixed the string-too-long problem, but the behaviour still persists, and manifests itself in a core dump in `Dreplace()` (in `disc.c`). `edam` has an intricate disc-backed buffering system (which the Plan9port version of `sam` completely re-wrote. I can see why....!), and there seems there might be an unhandled edge-case in the `edam` code that synchronises the in-memory buffer with its on-disc backing. This may well take a bit of digging to get to the bottom of.

**Comment by phonologus** [comment]
Still no fix yet, but as a point of interest, the `edam-bug` file trips a line-buffer limit in `qed`, too. `qed` handles it gracefully (if you can call `?z~25 ?l` graceful!) without dumping core.

**Comment by phonologus** [comment]
Apologies for the delay...

I'm just about to push a fix. Turned out to be quite simple. The `String` struct was declared with dimensions of type `short`, which would overflow silently into a negative number, which then triggered the panics/core dumps. A fix for `qed` is still pending.

**Comment by phonologus** [comment]
Quick update: I have pushed a commit to my `qed-new` repo which allows `qed` to process the `edam-bug` file successfully.

**Comment by phonologus** [comment]
OK, I've just pushed a fairly big patchset to qed-new, including fixes to `install` so that the permissions come out right.

My own personal repo (I use `fossil` as my SCM) had become slightly out of sync with the github version, so the previous github commit didn't contain all the changes I'd made. With this last commit we're all up-to-date, and a `qed` built from the current checkout should process your `edam-bug` file with no problems :)
